table Sales_Data1
	lineageTag: ca2bcbdc-52b7-4cf8-981f-bb39db5fbcb4

	measure revenue = SUMX(Sales_Data1,Sales_Data1[QUANTITYORDERED]*Sales_Data1[PRICEEACH])
		formatString: 0
		lineageTag: 789f8c45-f041-4ece-bdfa-96596d5a74e9

	measure 'total order' = DISTINCTCOUNT(Sales_Data1[ORDERNUMBER])
		formatString: 0
		lineageTag: 828c7bf5-c30d-42ec-be48-00a5dafa7641

	measure 'total customers' = DISTINCTCOUNT(Sales_Data1[CUSTOMERNAME])
		formatString: 0
		lineageTag: 0a42c8c2-5345-4213-a248-70b6d54a4697

	measure 'avg.quantity per order' = AVERAGE(Sales_Data1[QUANTITYORDERED])
		lineageTag: 24d6cff2-daba-4400-a110-e1741231791f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'avg.order value' = [revenue]/[total order]
		lineageTag: f9303c8f-8dc8-4c64-aa8e-c27b6a3dddaf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ORDERNUMBER
		dataType: int64
		formatString: 0
		lineageTag: 2a1f7a7e-980b-475b-b6a2-e7eb094cca36
		summarizeBy: sum
		sourceColumn: ORDERNUMBER

		annotation SummarizationSetBy = Automatic

	column QUANTITYORDERED
		dataType: int64
		formatString: 0
		lineageTag: a336d65f-ce00-468a-b997-30db13e220e7
		summarizeBy: sum
		sourceColumn: QUANTITYORDERED

		annotation SummarizationSetBy = Automatic

	column PRICEEACH
		dataType: int64
		formatString: 0
		lineageTag: c4df51b7-2a67-4c3a-a122-bd833bf14e7f
		summarizeBy: sum
		sourceColumn: PRICEEACH

		annotation SummarizationSetBy = Automatic

	column ORDERLINENUMBER
		dataType: int64
		formatString: 0
		lineageTag: 2a85d713-f328-424f-855c-1ff4885f3aba
		summarizeBy: sum
		sourceColumn: ORDERLINENUMBER

		annotation SummarizationSetBy = Automatic

	column ORDERDATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 674437e0-0c82-4798-bf33-ca27e42d87bb
		summarizeBy: none
		sourceColumn: ORDERDATE

		variation Variation
			isDefault
			relationship: 14a66a82-ecbb-41ff-8428-8642e0a53dad
			defaultHierarchy: LocalDateTable_2518d0c2-4970-4def-aad2-b8e2172d9a66.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column STATUS
		dataType: string
		lineageTag: 651c454e-a7dc-4d56-814f-83bfafc7b519
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column QTR_ID
		dataType: int64
		formatString: 0
		lineageTag: 7a7bc5e1-9196-4f96-9001-fd3fbadc12f9
		summarizeBy: count
		sourceColumn: QTR_ID

		annotation SummarizationSetBy = Automatic

	column MONTH_ID
		dataType: int64
		formatString: 0
		lineageTag: 24955716-0e98-402d-9aa8-b209dee9579f
		summarizeBy: count
		sourceColumn: MONTH_ID

		annotation SummarizationSetBy = Automatic

	column YEAR_ID
		dataType: int64
		formatString: 0
		lineageTag: fa2b3799-82a7-4632-a64e-153c4eeab385
		summarizeBy: count
		sourceColumn: YEAR_ID

		annotation SummarizationSetBy = Automatic

	column PRODUCTLINE
		dataType: string
		lineageTag: c4fbf5d7-f90f-4087-a9e6-d250977d715d
		summarizeBy: none
		sourceColumn: PRODUCTLINE

		annotation SummarizationSetBy = Automatic

	column PRODUCTCODE
		dataType: string
		lineageTag: 407bc413-fd58-4929-b0bf-a54af3fd53af
		summarizeBy: none
		sourceColumn: PRODUCTCODE

		annotation SummarizationSetBy = Automatic

	column CUSTOMERNAME
		dataType: string
		lineageTag: 60f79380-8285-4e1a-8cd7-48c4646cb460
		summarizeBy: none
		sourceColumn: CUSTOMERNAME

		annotation SummarizationSetBy = Automatic

	column ADDRESSLINE1
		dataType: string
		lineageTag: 066503c8-abfb-47fd-80a6-a158e8f816b9
		summarizeBy: none
		sourceColumn: ADDRESSLINE1

		annotation SummarizationSetBy = Automatic

	column CITY
		dataType: string
		lineageTag: a4acd3d7-f65e-46a1-ab57-1aacceb0743f
		summarizeBy: none
		sourceColumn: CITY

		annotation SummarizationSetBy = Automatic

	column STATE
		dataType: string
		lineageTag: a31b053c-d68a-4825-987d-43c4c3725657
		summarizeBy: none
		sourceColumn: STATE

		annotation SummarizationSetBy = Automatic

	column POSTALCODE
		dataType: string
		lineageTag: 075abdd9-90b4-4c8c-b400-9b0145f85e72
		summarizeBy: none
		sourceColumn: POSTALCODE

		annotation SummarizationSetBy = Automatic

	column COUNTRY
		dataType: string
		lineageTag: 113ed7c0-2faf-4124-b351-38414700c112
		summarizeBy: none
		sourceColumn: COUNTRY

		annotation SummarizationSetBy = Automatic

	column TERRITORY
		dataType: string
		lineageTag: 442a830f-9395-4466-b8fb-ff4ef4032837
		summarizeBy: none
		sourceColumn: TERRITORY

		annotation SummarizationSetBy = Automatic

	column CONTACTLASTNAME
		dataType: string
		lineageTag: a22f745f-dae4-4754-8d23-fcb1b986d7e9
		summarizeBy: none
		sourceColumn: CONTACTLASTNAME

		annotation SummarizationSetBy = Automatic

	column CONTACTFIRSTNAME
		dataType: string
		lineageTag: 2ac68880-9df1-44e9-a28c-7735b4381b1d
		summarizeBy: none
		sourceColumn: CONTACTFIRSTNAME

		annotation SummarizationSetBy = Automatic

	column DEALSIZE
		dataType: string
		lineageTag: 1789d4fb-e2e2-41f5-a273-1bc147293657
		summarizeBy: none
		sourceColumn: DEALSIZE

		annotation SummarizationSetBy = Automatic

	column 'TOTAL REVENUE' = 'Sales_Data1'[QUANTITYORDERED]*'Sales_Data1'[PRICEEACH]
		formatString: 0
		lineageTag: fcefaba9-0fc1-4653-8324-f2dbf18626a9
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Sales_Data1 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\acer\Downloads\Day - 11 to Day 13 Also use in 23, 24 Parts - Vehicle Product Sales Data - Copy.xlsx"), null, true),
				    Sales_Data1_Sheet = Source{[Item="Sales_Data1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sales_Data1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ORDERNUMBER", Int64.Type}, {"QUANTITYORDERED", Int64.Type}, {"PRICEEACH", type number}, {"ORDERLINENUMBER", Int64.Type}, {"ORDERDATE", type datetime}, {"STATUS", type text}, {"QTR_ID", Int64.Type}, {"MONTH_ID", Int64.Type}, {"YEAR_ID", Int64.Type}, {"PRODUCTLINE", type text}, {"PRODUCTCODE", type text}, {"CUSTOMERNAME", type text}, {"ADDRESSLINE1", type text}, {"ADDRESSLINE2", type text}, {"CITY", type text}, {"STATE", type text}, {"POSTALCODE", type any}, {"COUNTRY", type text}, {"TERRITORY", type text}, {"CONTACTLASTNAME", type text}, {"CONTACTFIRSTNAME", type text}, {"DEALSIZE", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [ORDERNUMBER] <> null and [ORDERNUMBER] <> ""),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows",null,"NA",Replacer.ReplaceValue,{"STATE"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value",{{"POSTALCODE", type text}}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Changed Type1",null,"NA",Replacer.ReplaceValue,{"POSTALCODE"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value1",{{"POSTALCODE", type text}}),
				    #"Removed Errors" = Table.RemoveRowsWithErrors(#"Changed Type2", {"POSTALCODE"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Removed Errors",{"ADDRESSLINE2"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns",{{"PRICEEACH", Int64.Type}}),
				    #"Removed Errors1" = Table.RemoveRowsWithErrors(#"Changed Type3"),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Removed Errors1",{{"ORDERDATE", type date}})
				in
				    #"Changed Type4"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

